# We use this to test the scala-cve workflow.
name: Scala CVE

on:
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
  schedule:
  - cron: 0 14 * * 1

jobs:
  invoke:
    name: test
    uses: ./.github/workflows/scala-cve.yaml
    with:
      open_issue: false
      scala_root: test/scala/test-project
    secrets: inherit
