name: Typescript Release

on:
  release:
    types:
      - "created" # triggered by Bump Version creating a release
  workflow_call:
    inputs:
      node_version:
        description: "What version of node should be used when running tests/publishing."
        required: false
        default: "20"
        type: string
      pre_publish_steps:
        description: "Any steps to run before publishing begins (like `build.js; cd dist`)"
        required: false
        default: ""
        type: string

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: "https://registry.npmjs.org"
      - name: Pre-publish steps
        if: ${{ inputs.pre_publish_steps }} != ""
        run: ${{inputs.pre_publish_steps}}
      - run: npm publish
